### ISSUE TITLE
How can I add Custom Span name to OpenTelemetry::Instrumentation::Redis

### ISSUE THREAD

**Issue by Rahul240599** [open-telemetry/opentelemetry-ruby-contrib#1001]
I am using otel sdk to configure redis traces using OpenTelemetry::Instrumentation::Redis

this is how i am currently defining the configs for OpenTelemetry::Instrumentation::Redis inside a method otel_config

```
conf['OpenTelemetry::Instrumentation::Redis'] = {
          peer_service: false,
          trace_root_spans: false,
          enabled: config.redis_trace_enabled?
        }
```
        
        
and then configuring the sdk as 
```

::OpenTelemetry::SDK.configure do |c|
          c.use_all otel_config(config)
        end
        
```
        
 My redis traces are coming in with name as GET, MGET, DEL
 but i want that my span name should start with a prefix "Redis"
 
 for eg: "Redis GET", "Redis DEL", etc
 
 Can anyone tell me how to do that from the configs for OpenTelemetry::Instrumentation::Redi
 and also how can i additonal attributes/tags to the redis spans?
 
 
 some ss of spans i am getting as of now
 
<img width="1475" alt="image" src="https://github.com/open-telemetry/opentelemetry-ruby-contrib/assets/74906060/deaec8c6-45b3-4689-9bb8-d3ea7a8aded1">

<img width="381" alt="image" src="https://github.com/open-telemetry/opentelemetry-ruby-contrib/assets/74906060/bd6db0af-c65b-42b7-92bf-ada3bd9c2888">

**Comment by arielvalentin** [comment]
The OTel Collector is the most appropriate place to customize spans. 

https://opentelemetry.io/docs/collector/transforming-telemetry/

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanprocessor
