### ISSUE TITLE
Add the `db.collection.name` attribute to `pg` instrumentation

### ISSUE THREAD

**Issue by kaylareopelle** [open-telemetry/opentelemetry-ruby-contrib#1059]
The [`db.collection.name`](https://opentelemetry.io/docs/specs/semconv/database/database-spans/#:~:text=Required-,db.collection.name,-string) attribute is conditionally required for Database spans.

Currently, `pg` instrumentation does not emit this attribute.

Update the `opentelemetry-instrumentation-pg` library to emit this attribute.

**Comment by kaylareopelle** [comment]
cc @hannahramadan

**Comment by hannahramadan** [comment]
I'll grab this one!
