### ISSUE TITLE
Net::HTTP - Add ability to exclude domains

### ISSUE THREAD

**Issue by johnnyshields** [open-telemetry/opentelemetry-ruby-contrib#107]
Rack instrumentation has an option `untraced_endpoints` which can be used to exclude tracing things like `/health`

I'd like to request an analogous feature for `Net::HTTP`. This can be used to filter out requests to Bugsnag/Sentry/etc. which are sent randomly in a non-webserver thread. Perhaps we could do `untraced_hosts`

**Comment by ahayworth** [comment]
I believe we would welcome such a PR! This seems like it could be useful in a variety of circumstances.

**Comment by johnnyshields** [comment]
PR raised: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/108
