### ISSUE TITLE
`OpenTelemetry::Instrumentation::ActiveJob::Handlers.unsubscribe` failed with the exception `uninitialized constant OpenTelemetry::Instrumentation::ActiveSupport::Notifications`

### ISSUE THREAD

**Issue by lavoiesl** [open-telemetry/opentelemetry-ruby-contrib#1076]
**Description of the bug**

When calling `OpenTelemetry::Instrumentation::ActiveJob::Handlers.unsubscribe`, it fails with:
`uninitialized constant OpenTelemetry::Instrumentation::ActiveSupport::Notifications`.

Bug report to capture this comment: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/677/files#r1686574263

**Share details about your runtime**

```
Operating system details: macOS
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.1.1"
RUBY_DESCRIPTION: "ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]"
```

**Comment by arielvalentin** [comment]
Thanks for identifying this problem and filing this issue.

Do you have any availability to help with a PR to address this problem?

**Comment by lavoiesl** [comment]
Here we go 🙂 
https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1078
