### ISSUE TITLE
Sequel instrumentation adapter

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby-contrib#11]
Convert Datadog instrumentation for Sequel to OpenTelemetry. 

See
  * [Datadog porting guide](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/instrumentation/datadog-porting-guide.md)
  * [Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions)
  * [Datadog implementation](https://github.com/DataDog/dd-trace-rb/tree/master/lib/ddtrace/contrib/sequel)

**Comment by jrgns** [comment]
Updated link to the porting guide: https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/datadog-porting-guide.md

**Comment by qnm** [comment]
Is anyone working on this? I need it to migrate from beelines to otel, so may do it if no-one else is doing it!

**Comment by arielvalentin** [comment]
@qnm Thank you for being willing to help!

We have very limited capacity and are in need of additional maintainers to help with instrumentation. 

Please open a PR at your earliest convenience!

**Comment by jrgns** [comment]
@qnm  I just created a PR for it - https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/672
