### ISSUE TITLE
pg test suite failures

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#1111]
The nightly build for queue started failing with what seems to be gem related to activerecord gem dependencies. 

```console
🔎 Appraising pg_1.3
  Downloading activerecord-3.2.14 revealed dependencies not in the API or the
  lockfile (activesupport (= 3.2.14), activemodel (= 3.2.14), arel (~> 3.0.2),
  tzinfo (~> 0.3.29)).
  Running `bundle update activerecord` should fix the problem.
```

cc: @ahayworth as the current maintainer of the pg instrumentation.

https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/10335505991/job/28610139946

**Comment by kaylareopelle** [comment]
Fixed in #1112 by putting a bottom constraints on the version of activerecord that could be installed
