### ISSUE TITLE
revert client hooks

### ISSUE THREAD

**Issue by ericmustin** [open-telemetry/opentelemetry-ruby-contrib#115]
We don't want to own these, they exceed the scope of what belongs in the `-contrib` repo, and need to revert:

- https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/71
- https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/62

The appropriate approach is to help users author their own http instrumentations which they can modify how they please.

There's been lots of SIG discussion on this, please review relevant agenda and sig mtgs for more context.

**Comment by plantfansam** [comment]
Tickets for docs on writing own instrumentation: https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/104

**Comment by ericmustin** [comment]
cc @nozik as you were the original contributor here, wanted to give you the heads up that we've made the decision to revert all hooks, and wait for hooks to go through the OTEP process before supporting them.

Working on docs for how to bring / write your own instrumentation for ruby, and submit to the registry, so that your use case is better supported in the future.

I genuinely appreciate the work and effort you brought to this and I apologize for the wasted cycles. In the future we'll try to reach these conclusions earlier to avoid you spinning your wheels.

**Comment by nozik** [comment]
@ericmustin No worries, thanks for letting me know
