### ISSUE TITLE
Change in behavior in activerecord from 6.1 to 7.0+

### ISSUE THREAD

**Issue by mrsimo** [open-telemetry/opentelemetry-ruby-contrib#1183]
**Description of the bug**

In Rails 6.1 (and 6.0) there used to be an ActiveRecord span for each read query in the form of `Model.find_by_sql`. We found a few uses for this span, even if the underlaying query was also reported by the lower level library instrumentation as well.

With Rails 7.0 this has changed and only a few queries have this. For instance, `Post.first` doesn't create a `Post.find_by_sql` span, but a `post.comments` does create a `Comment.find_by_sql`. In Rails 6.1 there'd both of them.

**Share details about your runtime**

My reproduction steps were run with `ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]`, latest opentelemetry gems and various Rails versions (as seen in the script).

**Share a simplified reproduction if possible**

[Here's a gist](https://gist.github.com/mrsimo/11c45868554994a4b4920f764562965b) with a script to reproduce this. The output:

```
❯ for rails in 6.1 7.0 7.1 7.2; do echo "Rails version: $rails"; RAILS_VERSION=$rails ruby run.rb 1> /dev/null; done
Rails version: 6.1
OpenTelemetry::Instrumentation::Mysql2: select - {"db.statement"=>"SELECT `posts`.* FROM `posts` ORDER BY `posts`.`id` ASC LIMIT ?"}
OpenTelemetry::Instrumentation::ActiveRecord: Post.find_by_sql - {}
OpenTelemetry::Instrumentation::Mysql2: select - {"db.statement"=>"SELECT `comments`.* FROM `comments` WHERE `comments`.`post_id` = ?"}
OpenTelemetry::Instrumentation::ActiveRecord: Comment.find_by_sql - {}
Rails version: 7.0
OpenTelemetry::Instrumentation::Mysql2: select - {"db.statement"=>"SELECT `posts`.* FROM `posts` ORDER BY `posts`.`id` ASC LIMIT ?"}
OpenTelemetry::Instrumentation::Mysql2: select - {"db.statement"=>"SELECT `comments`.* FROM `comments` WHERE `comments`.`post_id` = ?"}
OpenTelemetry::Instrumentation::ActiveRecord: Comment.find_by_sql - {}
Rails version: 7.1
OpenTelemetry::Instrumentation::Mysql2: select - {"db.statement"=>"SELECT `posts`.* FROM `posts` ORDER BY `posts`.`id` ASC LIMIT ?"}
OpenTelemetry::Instrumentation::Mysql2: select - {"db.statement"=>"SELECT `comments`.* FROM `comments` WHERE `comments`.`post_id` = ?"}
OpenTelemetry::Instrumentation::ActiveRecord: Comment.find_by_sql - {}
Rails version: 7.2
OpenTelemetry::Instrumentation::Mysql2: select - {"db.statement"=>"SELECT `posts`.* FROM `posts` ORDER BY `posts`.`id` ASC LIMIT ?"}
OpenTelemetry::Instrumentation::Mysql2: select - {"db.statement"=>"SELECT `comments`.* FROM `comments` WHERE `comments`.`post_id` = ?"}
OpenTelemetry::Instrumentation::ActiveRecord: Comment.find_by_sql - {}
```

**Comment by arielvalentin** [comment]
@mrsimo thank you for sharing these findings.

We could use your help making the active record instrumentation better. Would you be interested in helping us by contributing compatibility changes?

**Comment by xuan-cao-swi** [comment]
> Is there any intention to switch ActiveRecord instrumentation to ActiveSupport notifications?

I recall there were gaps between the notification approach and monkey patching from our last discussion. Are these issues still persistent?

The payload name is too general ([see discussion](https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/218#issuecomment-1881920888)), but it might help reduce span name cardinality.

Also, there are discussion about the [timing issue](https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/218#issuecomment-2034607745) from callback.

**Comment by arielvalentin** [comment]
Yes the limitations  remain with using notifications.
