### ISSUE TITLE
kafka integration test are failing on ppc64le 

### ISSUE THREAD

**Issue by adilhusain-s** [open-telemetry/opentelemetry-ruby-contrib#122]
**Description of the bug**
the kafka test cases are failing becuase docker image confluent/kafka  isn't  available for ppc64le

**Share details about your runtime**

Operating system details: Linux, RHEL 8.5 
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.0.0"
RUBY_DESCRIPTION: "ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]"

is it possible to use apache kafka for integration  testing instead of using confluent/kafka?

**Comment by ahayworth** [comment]
@adilhusain-s If you have any interest in making a PR that uses the Apache kafka image, I think we would be open to it! I don't have anything that runs on `ppc64le` architecture so it would be rather difficult for me to assert that it works as expected, but it sounds like maybe you have that hardware available. 😄

**Comment by adilhusain-s** [comment]
thanks for the response, 
I tested with apache kafka, but the test cases are failing with following error:
[root@2d8317295fb6 opentelemetry-ruby-contrib]# cd instrumentation/rdkafka/                                                                                                                                      
[root@2d8317295fb6 rdkafka]# bundle exec rake test                                                                                                                                                               
Run options: --seed 12634                                                                                                                                                                                        
                                                                                                                                                                                                                 
# Running:                                                                                                                                                                                                       
                                                                                                                                                                                                                 
A, [2022-09-15T05:50:58.051587 #121061]   ANY -- : rdkafka: [thrd:127.0.0.1:29092/bootstrap]: 127.0.0.1:29092/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security. Protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 0ms in state APIVERSION_QUERY)                                                                       
A, [2022-09-15T05:50:58.207844 #121061]   ANY -- : rdkafka: [thrd:127.0.0.1:29092/bootstrap]: 127.0.0.1:29092/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security. Protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 0ms in state APIVERSION_QUERY, 1 identical error(s) suppressed)                                      
A, [2022-09-15T05:51:30.143005 #121061]   ANY -- : rdkafka: [thrd:127.0.0.1:29092/bootstrap]: 127.0.0.1:29092/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security. Protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 0ms in state APIVERSION_QUERY, 5 identical error(s) suppressed)                                      
     


however, when I installed the confluent-kafka locally, I was able to pass the test cases successfully.
