### ISSUE TITLE
Gems' homepage points to a missing location

### ISSUE THREAD

**Issue by kjg** [open-telemetry/opentelemetry-ruby-contrib#128]
It looks like Currently most/all of the gems' [configured homepage](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/5815a34093764de2838d7a07b51778df76be83db/instrumentation/active_support/opentelemetry-instrumentation-active_support.gemspec#L19) points to https://github.com/open-telemetry/opentelemetry-contrib, however there doesn't appear to be a repo there. This repo is currently at https://github.com/open-telemetry/opentelemetry-ruby-contrib.

We might want to update all gems published by this repo to point to this repo url as their homepage instead. Would it make sense to extract the homage for all the gems to read from a constant or otherwise dynamically set the homepage as part of the publish process?

**Comment by arielvalentin** [comment]
doah! Good find @kjg and sorry it took so long for me to notice!
