### ISSUE TITLE
Open Release Request uses deprecated actions command `set-output`

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#144]
Please review the blog post and update the action

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/3231243639

**Comment by ahayworth** [comment]
```
opentelemetry-ruby-contrib on  main via 💎 v3.1.2
zsh ❯ git grep -c set-output
.github/actions/test_gem/action.yml:6
.github/workflows/ci.yml:39

opentelemetry-ruby-contrib on  main via 💎 v3.1.2
zsh ❯ cd ../opentelemetry-ruby

opentelemetry-ruby on  main via 💎 v3.1.2
zsh ❯ git grep -c set-output
.github/actions/test_gem/action.yml:6
.github/workflows/ci.yml:10

opentelemetry-ruby on  main via 💎 v3.1.2
```

Well, this will be fun...

**Comment by ahayworth** [comment]
Oh, actually not too bad., see #145 and open-telemetry/opentelemetry-ruby/pull/1389
