### ISSUE TITLE
ActionPack Instrumentation - change default options, remove span_naming, add source code attributes

### ISSUE THREAD

**Issue by richardmcmillen** [open-telemetry/opentelemetry-ruby-contrib#159]
Since https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/123 if you wish to use the default span naming option (rails route) you no longer have an attribute with the controller#action in it.

I think that being able to select what span naming you want, and additionally having access to the alternative naming method as regular attributes is important.

I'd like to propose an amendment so that:

1. Attribute(s) exists on the span which represent the Controller and the Action which was called. These would always be present - there is a related comment here about following the source code Semantic Conventions for this: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/123#discussion_r970763772
2. `http.route` is enabled by default - `enabled_recognize_route` defaults to `true`. After https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/123 the default is to use the span naming which uses recognize route, since this cost is already being paid in the default configuration format, and it is memoized, it seems like it would be ok to add it by default.
3. The `span_naming` configuration option is removed in favour of using the `enable_recognize_route` option. It's default should be `true`. When it is `false` the `http.route` attribute is not added, the span name is in the format of `controller#action` (the current :controller_action logic), and the recognize route code is not executed at all.

This reduces the configuration surface area while keeping intent (avoid the expensive code).

I would be more than happy to put together a pull request if this an accepted approach.

----

Links:

Span naming addition: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/123
Fix span naming config: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/157

**Comment by ahayworth** [comment]
I haven't followed this discussion closely - but @robertlaurin, @arielvalentin, and @dmathieu have. Do any of you have thoughts on this?
