### ISSUE TITLE
Rake instrumentation adapter

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby-contrib#17]
Convert Datadog instrumentation for Rake to OpenTelemetry. 

See
  * [Datadog porting guide](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/adapters/datadog-porting-guide.md)
  * [Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions)
  * [Datadog implementation](https://github.com/DataDog/dd-trace-rb/tree/master/lib/ddtrace/contrib/rake)

**Comment by yoheyk** [comment]
Can I take this one? We already have a kind of patch for this. It's going to be a very simple instrumentation.
Or should I wait until the "semantic convention" to reach a conclusion?

**Comment by plantfansam** [comment]
@yoheyk definitely make a PR! Thanks!
