### ISSUE TITLE
idea: figure out how to more declaratively manage instrumentation dependencies and transitive dependencies

### ISSUE THREAD

**Issue by ahayworth** [open-telemetry/opentelemetry-ruby-contrib#176]
Hi hello, it's me - a maintainer pretending to be the amazing release engineer that is @arielvalentin! Having attempted to fill in for him the past few days, I've found myself a little confused about how we're releasing things.

As I understand things, we basically have to:
- Keep track of which instrumentation versions have been released to rubygems and make sure we always have the latest releases pushed. This is a _manual_ process!
- Keep track of the various sub-dependency chains (`-rails` depends on its various sub-gems; `-all` on its various sub-gems _including_ `-rails` 🙃) and release things in the correct order.
- Any gem release that needs transitive dependency updates is complex, and involves at least 3 PRs (one PR to release the sub-dependency, a second PR to bump the required version in the actual gem we want to release, and finally a third PR to release the actual thing we wanted to release)
- Remember the foibles of the release tooling (CI doesn't kick off correctly, updates to `main` can wreak havoc, etc).

Each release feels like a ton of work. With all that in mind I want to propose the following:
1. Centrally track gem dependencies in a YAML file in the repo. I think referencing our dependency chains in _one_ place will go a long way towards helping us remember what the heck we actually have to do, and then we can build smarter tooling upon it.
2. Replace `toys` with something that the current maintainers understand more readily. `toys` seems nice in a lot of ways, but it does a _lot_ of work behind the scenes that feels mysterious to us. I'd much rather have something less-magic that actually results in us understanding the tooling better. We can build automation around smaller, discrete pieces as needed.
3. Coordinate version bumps better via automation. For example, if we change `-action_pack`, then something should _automatically_ enforce that `-rails` _and_ `-all` have their dependencies updated automatically.
4. Have automation that tells us what needs to be released, rather than ... trying to just divine it by staring at the codebase.

I don't know that this is necessarily the right approach or even captures all of the annoying bits. This is just what annoys _me_, and frankly the complexity of it all contributes to me being afraid to do my part in releasing (I'm afraid that I'll mess it up unless I'm paying _extraordinarily_ close attention).

Please feel free to debate and/or tear these ideas apart. We don't have to do all of them; and what we _do_ decide to work on can be done bit by bit.

**Comment by ahayworth** [comment]
It should also be noted that I am volunteering to do most/all of the work to make this happen. It's not the most rewarding work, but I feel like it's the least I can do given that I've not been really doing my fair share releasing things around here. 😆

**Comment by plantfansam** [comment]
I think this is important work to do. Maybe we can start by sketching out what the centralized dependency definer would look like? Anyone know of prior art on this type of thing? Seems like a solved problem.
