### ISSUE TITLE
Feature Request - New Resource Detector - dockerCGroupV1Detector #2353

### ISSUE THREAD

**Issue by tomerfriedman** [open-telemetry/opentelemetry-ruby-contrib#179]
- Same as the @opentelemetry/resource-detector-docker for NodeJS
- Add Container Tag attributes

**Comment by tomerfriedman** [comment]
https://github.com/DataDog/dd-trace-rb/blob/f1a8956baa5c1f552c89f8a6c72cc04e075e5d5a/lib/datadog/core/environment/container.rb

**Comment by ahayworth** [comment]
I think we'd be happy to accept a PR that added this resource detector. At the moment, we are a little constrained by resources and unlikely to add this ourselves right away - but if anyone in the community is interested, we'd be happy to review such a PR and work with you to get it merged. 😄
