### ISSUE TITLE
Add docs for _CONFIG_OPTS env var

### ISSUE THREAD

**Issue by plantfansam** [open-telemetry/opentelemetry-ruby-contrib#208]
We [support](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/base/lib/opentelemetry/instrumentation/base.rb#L324-L344) configuring various instrumentations with a specially formatted env var. We should document this feature.

**Comment by prathamesh-sonpatki** [comment]
@plantfansam @arielvalentin Is this still relevant? Can I pick this up?

**Comment by arielvalentin** [comment]
Yes please! The docs would be targeted against this repo: https://github.com/open-telemetry/opentelemetry.io/tree/main/content/en/docs/instrumentation/ruby

and published to https://opentelemetry.io/docs/instrumentation/ruby/

**Comment by arielvalentin** [comment]
@prathamesh-sonpatki I personally do not have a preference and I am not a very good technical writer 🙈 

@cartermp what are your thoughts on this? Is there any prior art for documenting language specific environment configuration variables?

**Comment by cartermp** [comment]
Yes! We can figure out the right place, but there is precedent:

https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/
https://github.com/open-telemetry/opentelemetry.io/pull/2196
