### ISSUE TITLE
Add db.operation to Dalli instrumentation

### ISSUE THREAD

**Issue by plantfansam** [open-telemetry/opentelemetry-ruby-contrib#209]
We should have a `db.operation` attribute in Dalli instrumentation. See https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/dalli/lib/opentelemetry/instrumentation/dalli/patches/server.rb#L14.

**Comment by prathamesh-sonpatki** [comment]
@arielvalentin Is this still relevant? Can I pick this up?

**Comment by arielvalentin** [comment]
Maybe? @plantfansam could you provide more details into what the `db.operation` should be vs `db.statement`?

https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/database/#call-level-attributes

**Comment by plantfansam** [comment]
> Maybe? @plantfansam could you provide more details into what the `db.operation` should be vs `db.statement`?

Absolutely! So per the [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#call-level-attributes), `db.operation` is meant to be the name of the operation being executed. So in MYSQL it might be `DELETE` or `SELECT`.

DB _statement_ is meant to be the entire statement that's being executed. So that value might be something like `SELECT * FROM wuser_table; SET mykey "WuValue"`.

As I see it, `db.operation` may allow a coarser-grained perspective on database spans when `db.statement` is redacted, and this is valuable work.

**Comment by arielvalentin** [comment]
I appreciate the guidance and context here. 

Probably want to take these comments into consideration as well:

> The span name SHOULD be set to a low cardinality value representing the statement executed on the database. It MAY be a stored procedure name (without arguments), DB statement without variable arguments, operation name, etc. Since SQL statements may have very high cardinality even without arguments, SQL spans SHOULD be named the following way, unless the statement is known to be of low cardinality: <db.operation> <db.name>.<db.sql.table>, provided that db.operation and db.sql.table are available. If db.sql.table is not available due to its semantics, the span SHOULD be named <db.operation> <db.name>. It is not recommended to attempt any client-side parsing of db.statement just to get these properties, they should only be used if the library being instrumented already provides them. When it's otherwise impossible to get any meaningful span name, db.name or the tech-specific database name MAY be used.

**Comment by prathamesh-sonpatki** [comment]
Awesome. Thanks. I will get back soon :)
