### ISSUE TITLE
Drop Support for DelayedJob

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#245]
DelayedJob ActiveRecord is reporting deprecation warnings for active record and there does not seem to be any active development: 

```console
DEPRECATION WARNING: ActiveRecord::Base.default_timezone is deprecated and will be removed in Rails 7.1.
Use `ActiveRecord.default_timezone` instead.
```

https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/3790545254/jobs/6445243399#step:5:232

A recent example of the lead time to get a PR merged to deal with an issue that was breaking our build took almost 4 months to be merged up stream: https://github.com/collectiveidea/delayed_job/pull/1169

I think we should drop support for DelayedJob.

**Comment by ahayworth** [comment]
<img width="517" alt="Screenshot 2023-01-20 at 7 08 16 PM" src="https://user-images.githubusercontent.com/1781907/213831223-38a8d304-24db-4c53-9cc1-1e5f824d6c0e.png">

It does look like there is some life in the repo, even if things are a little slow. 🤷 

---

I don't know if I agree that we should drop it ... after all, that deprecation warning has nothing to do with our code or how we instrument it, right?

I think we should wait to make a decision until Rails 7.1 is released. It won't just break our test suite, it'll break for non-instrumented use cases and that should generate sufficient upstream pressure for us to make a better decision. We'll _know_ then if it's just sluggish development, or if it's actually dead.

---

I will also admit that I don't hold this opinion very strongly. I could be persuaded either way!

**Comment by arielvalentin** [comment]
It was incompatible much earlier than Rails 7.1:

https://github.com/open-telemetry/opentelemetry-ruby/issues/1234

I don't want that to happen again.

**Comment by rscnt** [comment]
Maybe it could be extracted into a different gem?
