### ISSUE TITLE
Audit SimpleCov Usage

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#246]
It looks like our usage of SimpleCov is a bit inconsistent, some gems do not report code coverage at all while others require at least 85% coverage. 

What is our code coverage policy? Should we require it for all gems in the contrib repo?

**Comment by scbjans** [comment]
Below the current inventory of code coverage requirements:
|gem|minimum_coverage|remarks|
|---|----------------|-------|
|opentelemetry-propagator-ottrace|85|only when `ENV['ENABLE_COVERAGE']` is set|
|opentelemetry-propagator-xray|-||
|opentelemetry-instrumentation-que|-||
|opentelemetry-instrumentation-http_client|-||
|opentelemetry-instrumentation-mysql2|-||
|opentelemetry-instrumentation-sinatra|-||
|opentelemetry-instrumentation-sidekiq|-||
|opentelemetry-instrumentation-dalli|-||
|opentelemetry-instrumentation-racecar|-||
|opentelemetry-instrumentation-redis|-||
|opentelemetry-instrumentation-ruby_kafka|-||
|opentelemetry-instrumentation-concurrent_ruby|-||
|opentelemetry-instrumentation-active_model_serializers|-||
|opentelemetry-instrumentation-rake|-||
|opentelemetry-instrumentation-action_view|-||
|opentelemetry-instrumentation-bunny|-||
|opentelemetry-instrumentation-all|-||
|opentelemetry-instrumentation-aws_sdk|-||
|opentelemetry-instrumentation-active_record|-||
|opentelemetry-instrumentation-faraday|-||
|opentelemetry-instrumentation-resque|-||
|opentelemetry-instrumentation-rdkafka|-||
|opentelemetry-instrumentation-pg|-||
|opentelemetry-instrumentation-ethon|-||
|opentelemetry-instrumentation-lmdb|-||
|opentelemetry-instrumentation-active_support|-||
|opentelemetry-instrumentation-http|-||
|opentelemetry-instrumentation-graphql|-||
|opentelemetry-instrumentation-trilogy|-||
|opentelemetry-instrumentation-net_http|-||
|opentelemetry-instrumentation-rack|-||
|opentelemetry-instrumentation-action_pack|-||
|opentelemetry-instrumentation-mongo|-||
|opentelemetry-instrumentation-restclient|-||
|opentelemetry-instrumentation-koala|-||
|opentelemetry-instrumentation-active_job|-||
|opentelemetry-instrumentation-excon|-||
|opentelemetry-instrumentation-rspec|-||
|opentelemetry-instrumentation-base|85||
|opentelemetry-instrumentation-delayed_job|-||
|opentelemetry-instrumentation-rails|-||
|opentelemetry-resource_detectors|-||

Currently only one gem is actually required to have at least 85% coverage.
My personal preference would be to be consistent throughout this repo, which would also help new contributors to uphold coverage.

I currently don't have a lot of bandwidth; but if it's clear what the code coverage policy will be, I'm happy to at least fix the low-hanging fruit.
