### ISSUE TITLE
Feature Request: Sidekiq args on spans

### ISSUE THREAD

**Issue by julianajuliano** [open-telemetry/opentelemetry-ruby-contrib#254]
When debuging sidekiq issues it helps to know the arguments of the worker that failed, not only the job_class

I'd propose adding one more property to the span:

```
sidekiq {  
    job_class: 'ClassOfWorker',
    job_args: [3,5,'arg']
}


```

**Comment by arielvalentin** [comment]
Thanks for submitting this feature request unfortunately this is not something we will consider at this time. 

Generally speaking we avoid adding granular attributes with high-cardinality in a generic way for instrumentations, e.g. HTTP Request Parameters, Body, Job Arguments, etc... 

My recommendation is for you to enrich spans in your application and explicitly add parameters yourself using internal semantic attributes: https://opentelemetry.io/docs/instrumentation/ruby/manual/#add-attributes-to-a-span

Hope that helps.
