### ISSUE TITLE
ActiveRecord persistence class methods patch signature is too specific

### ISSUE THREAD

**Issue by ngoral** [open-telemetry/opentelemetry-ruby-contrib#269]
**Description of the bug**

Active Record instrumentation adds a patch for `create`, `new` and `update` class methods for AR models. And in a patch there is a specific signature copied from AR gem itself:
```ruby
def create(attributes = nil, &block)
```

We have other gems redefining these methods changing its signature, allowing to send additional options as a second argument

```ruby
  MyModel.create(my_model_attributes, additional_option: 'foo')
```

So when otel patches are applied, our code breaks.

Wouldn't it be better to be less specific in patches, e.g. replacing signature with something like
```ruby
def create(*args, **kwargs, &block)
``` 

I am happy to create a PR if you find this solution appropriate. By now we have to monkey-patch it ourselves =(

**Comment by arielvalentin** [comment]
@ngoral Thank you for reporting this issue. 

I would not classify this as a bug however I see why this is a usability problem for gems that _change_ the public ActiveRecord API methods, please see my reasoning here: 

https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/268#issuecomment-1377961595

> I am happy to create a PR if you find this solution appropriate. By now we have to monkey-patch it ourselves =(

We have a related issue to rewrite these instrumentations with ActiveSupport Notifications, which would eliminate the needs to patch methods on ActiveRecord directly and avoid running into issues like this. 

I PR to move the instrumentation to use ActiveSupport Notifications would be welcome!

https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/218

**Comment by ngoral** [comment]
@arielvalentin Thank you! My bad not seeing the issue you send, I've seached, but, obviously not good enough.

I've read your argumentation and see your position here, thank you. Also seen #218, and will take a better look at it.
