### ISSUE TITLE
ActionMailer instrumentation

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#293]
Convert Datadog instrumentation for ActionMailer to OpenTelemetry.

See

[Datadog porting guide](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/adapters/datadog-porting-guide.md)
[Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions)
[Datadog implementation](https://github.com/DataDog/dd-trace-rb/tree/a7c8aa5d81b67d136665dfb86d2345b783fb2290/lib/datadog/tracing/contrib/action_mailer)

**Comment by kaylareopelle** [comment]
Closed by #887 and #984
