### ISSUE TITLE
Sinatra exceptions are missing for erroneous spans

### ISSUE THREAD

**Issue by scbjans** [open-telemetry/opentelemetry-ruby-contrib#327]
https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/317 defers error handling from sinatra to the rack middleware. This only applies to marking a span as erroneous (see: https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/rack/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb#L155), not for adding the exception to it (see: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/317#issuecomment-1416297686)

Although I did review that PR, my conclusion was eventually that I messed up my own configuration; but apparently I messed that up as well :)

**Comment by scbjans** [comment]
I'm currently a bit low on bandwidth; so for our own installation I've pinned `opentelemetry-instrumentation-sinatra` to `0.21.3` which still works for us.
I'm happy to look into this myself in a couple of weeks.

**Comment by arielvalentin** [comment]
@rdoherty-fastly mind taking a look at this?
