### ISSUE TITLE
Ruby 2.7 EOL 2023-04-01

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#363]
Ruby 2.7 EoL 2023-04-01 https://www.ruby-lang.org/en/downloads/branches/ 

1. Drop compatibility testing
2. Update minimal Ruby version in gemspec
3. Document last supported version of contrib packages with Ruby 2.7

**Comment by arielvalentin** [comment]
@robbkidd I looked into adding a `post_install_message` that would print a deprecation warning if folks were using an earlier version of Ruby but it was surprisingly difficult to do since I could not check the target runtime ruby version without resorting to some shelling out shenanigans. 

I am just going to update the minimum ruby version required in the gemspecs.

**Comment by ahayworth** [comment]
@arielvalentin couldn't you use:
```
zsh ❯ pry
[1] pry(main)> RUBY_VERSION
=> "2.7.5"
[2] pry(main)>
```

?

**Comment by arielvalentin** [comment]
Unclear to me. 

https://github.com/rubocop/rubocop/issues/7137
