### ISSUE TITLE
Drop Support for Rack and Sinatra 1.x

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#364]
Sinatra depends on Rack 1.x which does not support `Rack::Events` API. 

- [ ] Write up documentation for last supported version of Sinatra 1.x
- [ ] Upgrade minimal gemspec dependencies to Sinatra > 2

**Comment by robbkidd** [comment]
Thank you for your service, ancient Rack and Sinatra. Retire and enjoy the pasture in peace.

![a grazing bovine](https://media.tenor.com/J5mFsv_HhecAAAAC/bull-grazing.gif)

**Comment by Anu-MT** [comment]
Hi,
I would like to work on this issue. Would you assign this to me?
As a first time contributor, any guidelines or help will be greatly appreciated.

**Comment by arielvalentin** [comment]
Thanks @Anu-MT !

The contributing guide is here: https://github.com/open-telemetry/opentelemetry-ruby-contrib#contributing

Please let me know if you have any questions.

**Comment by Anu-MT** [comment]
Hi,
I have removed the support for 1.x from instrumentation/sinatra/Appraisals. 
Could someone guide me on other changes to be made,please?

**Comment by arielvalentin** [comment]
@Anu-MT Take a look at the task list in the description to see what is left to do :)

**Comment by Anu-MT** [comment]
> @Anu-MT Take a look at the task list in the description to see what is left to do :)

Would you confirm the appropriate README.md file to add the documentation about last supported version of Sinatra 1.x,please ?

**Comment by arielvalentin** [comment]
Sure thing. Every gem in the contrib repo has a Readme and in the case of Sinatra it's here:

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/sinatra/README.md

**Comment by Anu-MT** [comment]
> Sure thing. Every gem in the contrib repo has a Readme and in the case of Sinatra it's here:
> 
> https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/sinatra/README.md

Thank you very much

**Comment by zacheryph** [comment]
I opened a new PR for this.  This issue makes note of documenting the support for version 1.x. Though given that the last version of Sinatra 1.x was January of 2017 I opted to not do this? What is the ... documented/documentation _support_ lifecycle for something like this?

If this is wanted, I can document the version required to support Sinatra 1.x in the readme.

**Comment by arielvalentin** [comment]
Great question @zacheryph 

We do not have this formally documented but here is an example of what we normally do:

https://github.com/open-telemetry/opentelemetry-ruby-contrib/tree/main/instrumentation/rails#version-compatibility
