### ISSUE TITLE
Action view instrumentation missing render layout

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [open-telemetry/opentelemetry-ruby-contrib#407]
Thanks for this great gem!! And excellent work!!

**Description of the bug**

Hello, i have noticed that my app is not generating action view render layout traces. I checked the source code and there isn`t a subscription for that event:
https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/07a8a9b375dbfbe4f2194e1516d968bb7a7a53db/instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/railtie.rb#L9-L14

This is intend? If not i can create this PR.

Rails subscription event:
https://guides.rubyonrails.org/active_support_instrumentation.html#render-layout-action-view

**Comment by arielvalentin** [comment]
@ahayworth I think this would be good to add. thoughts?

**Comment by arielvalentin** [comment]
@PedroAugustoRamalhoDuarte please open a PR for this if you have some time available.

Thanks!
