### ISSUE TITLE
X-Ray Compatible Feature Request

### ISSUE THREAD

**Issue by y-mitsuyoshi** [open-telemetry/opentelemetry-ruby-contrib#434]
The current aws-xray-sdk-ruby does not have the ability to trace sanitized SQL.
We want to use X-Ray as an APM like NewRelic and would like to add sanitized SQL.

The part I want to fix is the following record method.

https://github.com/aws/aws-xray-sdk-ruby/blob/5d482e76d86b7610d5fe8e404c44cd0bce9e9547/lib/aws-xray-sdk/facets/rails/active_record.rb

```ruby
      def record(transaction)
          payload = transaction.payload
          pool, conn = get_pool_n_conn(payload[:connection_id])

          return if IGNORE_OPS.include?(payload[:name]) || pool.nil? || conn.nil?
          # The spec notation is Rails < 6.1, later this can be found in the db_config
          db_config = if pool.respond_to?(:spec)
                        pool.spec.config
                      else
                        pool.db_config.configuration_hash
                      end
          name, sql = build_name_sql_meta config: db_config, conn: conn
          subsegment = XRay.recorder.begin_subsegment name, namespace: 'remote'
          # subsegment is nil in case of context missing
          return if subsegment.nil?
          subsegment.start_time = transaction.time.to_f
          subsegment.sql = sql
          XRay.recorder.end_subsegment end_time: transaction.end.to_f
        end
```

I would like to add **sql[:sanitized_query] = payload[:sql]** to the above code as follows.
```ruby
      def record(transaction)
          payload = transaction.payload
          pool, conn = get_pool_n_conn(payload[:connection_id])

          return if IGNORE_OPS.include?(payload[:name]) || pool.nil? || conn.nil?
          # The spec notation is Rails < 6.1, later this can be found in the db_config
          db_config = if pool.respond_to?(:spec)
                        pool.spec.config
                      else
                        pool.db_config.configuration_hash
                      end
          name, sql = build_name_sql_meta config: db_config, conn: conn
          sql[:sanitized_query] = payload[:sql]
          subsegment = XRay.recorder.begin_subsegment name, namespace: 'remote'
          # subsegment is nil in case of context missing
          return if subsegment.nil?
          subsegment.start_time = transaction.time.to_f
          subsegment.sql = sql
          XRay.recorder.end_subsegment end_time: transaction.end.to_f
        end
```

If it is too difficult, put SQL in the metadata.

**Comment by arielvalentin** [comment]
@y-mitsuyoshi thank you for your feedback! 

We currently provide a mechanism for adding `db.statement` obfuscation in most of the Database Specific Instrumentations, e.g.  and do not have plans on offering it directly through `ActiveRecord` at this time. 

Is the database specific instrumentation insufficient at this time?

**Comment by y-mitsuyoshi** [comment]
I personally prefer to have it because it is easier to investigate API performance through ActiveRecord and it is useful to visualize it in Grafana.
Other sdk's such as Java, Node.js, .NET, Go, etc. have this functionality.

**Comment by arielvalentin** [comment]
> Other sdk's such as Java, Node.js, .NET, Go, etc. have this functionality.

To confirm, you are saying that other Language SDKs include `db.statement` as an attribute on their ORMs _in addition_ to their Database Instrumentations?

**Comment by arielvalentin** [comment]
@y-mitsuyoshi I appreciate the links to the AWS SDK but my question was specifically about the OTel SDK. 

Our primary goal here is to have some similar compatibility and behavior between different implementations of the OTel SDK and it is agnostic to a specific vendor or backend. 

Our goal is to align our instrumentations with DB semantic conventions on Client spans, which for our purposes are the drivers: https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/database/ 

The specification does not make any AFAICT for ORM specific instrumentation so I hesitate to recommend that we add them to satisfy a specific vendor, which in this case is AWS. 

I have proposed a question in CNCF slack to see what other language specific maintainers are doing and see what other OTel SDKs are doing here: https://cloud-native.slack.com/archives/C01QZFGMLQ7/p1681828741903679 

If I do not get any feedback there I will post a discussion in the specification repo: https://github.com/open-telemetry/opentelemetry-specification/discussions?discussions_q=is%3Aopen+orm

**Comment by y-mitsuyoshi** [comment]
Sorry, I thought questions about the AWS SDK were supposed to be asked here.
My question is not about OTel, so you can close this issue.
Thank you for your answer.
