### ISSUE TITLE
Action View instrumentation fails if Rails is not defined

### ISSUE THREAD

**Issue by jmorrell** [open-telemetry/opentelemetry-ruby-contrib#475]
**Description of the bug**

When using the `OpenTelemetry::Instrumentation::ActionView` instrumentation outside of a Rails app the instrumentation will fail with an error:

```
ERROR -- : OpenTelemetry error: Instrumentation: OpenTelemetry::Instrumentation::ActionView unhandled exception during install: 
[{stack trace ...}] - uninitialized constant Rails
```

The instrumentation does not check for `::Rails` when [testing for compatibility](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/instrumentation.rb#L18)

```ruby
        present do
          defined?(::ActionView)
        end
```

but does require `::Rails::Railtie` when [installing the instrumentation](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/action_view/lib/opentelemetry/instrumentation/action_view/railtie.rb#L17)

```ruby
      # This Railtie sets up subscriptions to relevant ActionView notifications
      class Railtie < ::Rails::Railtie
```

If the instrumentation cannot be made to work without depending on `Rails::Railtie` then it would be good to update the detection to fail to install in the case that `Rails` is not defined:

```
        compatible do
          gem_version >= MINIMUM_VERSION && defined?(::Rails)
        end
```

**Share details about your runtime**

Operating system details: Linux, Ubuntu 20.04 LTS
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.2.1"
RUBY_DESCRIPTION: "ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]"

**Share a simplified reproduction if possible**

```rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "opentelemetry-api"
  gem "opentelemetry-sdk"
  gem 'opentelemetry-instrumentation-all'
  gem "actionview"
end

require "action_view"
require "opentelemetry-api"
require "opentelemetry-sdk"
require 'opentelemetry/instrumentation/all'

OpenTelemetry::SDK.configure do |c|
  c.service_name = 'Demo'
  c.use("OpenTelemetry::Instrumentation::ActionView", {})
end
```

**Comment by arielvalentin** [comment]
Thanks for reporting this. Are you using actionview without Rails?

**Comment by jmorrell** [comment]
@arielvalentin yes, this is the case in one of our larger services at Heroku. It's coming in as a dependency of `actionmailer`

**Comment by arielvalentin** [comment]
Thank you for sharing those details. 

Do you think that you or someone from your team would be willing to give us a hand with this?

**Comment by jmorrell** [comment]
I can open up a PR with the addition to the `compatible` check, though I was a little confused on how to go about testing it. I'll let y'all give me feedback on that in the PR though.
