### ISSUE TITLE
Sidekiq instrumentation not creating child spans with SDK 1.2.1

### ISSUE THREAD

**Issue by bolandoboy** [open-telemetry/opentelemetry-ruby-contrib#544]
Hi! I'm using the Sidekiq instrumentation with the option `propagation_style: :child`. This works fine with `opentelemetry-sdk` 1.2.0 but fails when upgrading to 1.2.1.

"Fails" here means that spans are not exported, tested with a minimal example using the `console` exporter.

Tracking down the problem, I think it all comes down to the same root cause of https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/535

1. `opentelemetry-sdk` 1.2.1 introduced this check in `OpenTelemetry::SDK::Trace::Tracer#start_span` ([MR here](https://github.com/open-telemetry/opentelemetry-ruby/pull/1412)):

https://github.com/open-telemetry/opentelemetry-ruby/blob/1159ec04aa62168c6a841273401b71c325fa5986/sdk/lib/opentelemetry/sdk/trace/tracer.rb#L32

2. In the Sidekiq instrumentation, unless you use the option `trace_processor_process_one: true`, the context is set as `untraced`:

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/cc244b9a1fff8bb2c79be90dd6bafd1a4212a426/instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/patches/processor.rb#L16

3. By the time the `process` span is going to be created, `extracted_context` is `untraced`. (Please note that for the default `propagation_style: :link` a new root span with its own context is created, and that works)

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/cc244b9a1fff8bb2c79be90dd6bafd1a4212a426/instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/server/tracer_middleware.rb#L33

4.  So for child spans `tracer.in_span` is used, which ends up calling the SDK `start_span` from point 1, which follow the `untraced` branch and, long story short, ends up creating a `OpenTelemetry::Trace::Span` instead of an `OpenTelemetry::SDK::Trace::Span`

`OpenTelemetry::Trace::Span` does nothing on `finish`, and spans are silently dropped:

https://github.com/open-telemetry/opentelemetry-ruby/blob/1159ec04aa62168c6a841273401b71c325fa5986/api/lib/opentelemetry/trace/span.rb#L154

(Edit: Not sure why some links are showing as snippets and others as huge links, sorry about that)

**Comment by arielvalentin** [comment]
Related https://github.com/open-telemetry/opentelemetry-ruby/issues/1495

**Comment by KirillKayumov** [comment]
Upgrading to `'opentelemetry-instrumentation-sidekiq', '0.24.4'` fixes the problem. Fix was added in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/580
