### ISSUE TITLE
Align messaging instrumentation operation names with semantic conventions

### ISSUE THREAD

**Issue by plantfansam** [open-telemetry/opentelemetry-ruby-contrib#561]
Per [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#operation-names), operation names around messaging systems should be `publish`, `receive`, and `process`

Grepping the repo, I see `send` spans in:

- [ ]  [activejob](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/912b3b97ddd68a61cfc7f749ffdf10c31e83afaa/instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/patches/active_job_callbacks.rb#L17)
- [ ]  [aws sdk](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/22796cb8141b3100c6ce94c25a15e31df3313464/instrumentation/aws_sdk/lib/opentelemetry/instrumentation/aws_sdk/handler.rb#L98)
- [ ] [bunny](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/38ff1eacad26c4a803940f3849eb2d2e0c1ab4b9/instrumentation/bunny/lib/opentelemetry/instrumentation/bunny/patch_helpers.rb#L19)
- [ ]  [delayed job](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/8f40eda20e0257bc740508b4b50758285d93e895/instrumentation/delayed_job/lib/opentelemetry/instrumentation/delayed_job/plugins/tracer_plugin.rb#L23)
- [ ]  [queue](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/6e89c92f189bc6e187da06ea2af4e38531b93601/instrumentation/que/lib/opentelemetry/instrumentation/que/patches/que_job.rb#L57)
- [ ]  [racecar](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/7b87ce557ed13ad80d135348050a64042d423165/instrumentation/racecar/lib/opentelemetry/instrumentation/racecar/patches/consumer.rb#L22)
- [ ]  [rdkafka](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/a84067bb6c8404a4c784b7291e16985ab859010d/instrumentation/rdkafka/lib/opentelemetry/instrumentation/rdkafka/patches/producer.rb#L22)
- [ ]  [resque](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/22796cb8141b3100c6ce94c25a15e31df3313464/instrumentation/resque/lib/opentelemetry/instrumentation/resque/patches/resque_module.rb#L38)
- [ ]  [ruby_kafka](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/22796cb8141b3100c6ce94c25a15e31df3313464/instrumentation/ruby_kafka/lib/opentelemetry/instrumentation/ruby_kafka/patches/client.rb#L27) (also [here](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/1c6ba39688b705f050127163383447f8d1245ed9/instrumentation/ruby_kafka/lib/opentelemetry/instrumentation/ruby_kafka/patches/producer.rb#L25))
- [ ]  [sidekiq](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/07a8a9b375dbfbe4f2194e1516d968bb7a7a53db/instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/client/tracer_middleware.rb#L26)

Unless I'm mistaken, all these should be "... publish". We should also probably check to make sure we're representing the messaging consumer with `process` spans.

**Comment by pollosp** [comment]
@arielvalentin as agreed into the SIG yesterday were are asking into [slack CNCF ](https://cloud-native.slack.com/archives/C01N7PP1THC/p1689776191164149) which is the status of the messaging OTEP and if we should stick to the current specification or we should switch to the new proposed.

**Comment by pollosp** [comment]
FYI. People from the messaging SIG has opened the PR https://github.com/open-telemetry/semantic-conventions/issues/198 and as well they told me this is a high priority task for them https://cloud-native.slack.com/archives/C02Q4AAHDSA/p1689796785715129?thread_ts=1689784544.587799&cid=C02Q4AAHDSA

**Comment by plantfansam** [comment]
I think we should keep this around, @github-actions bot

**Comment by michal-kazmierczak** [comment]
Hello, I'm eager to work on it. Would you mind assigning me?

**Comment by michal-kazmierczak** [comment]
I believe this issue was resolved in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/655
