### ISSUE TITLE
Can't install some instrumentations after installing opentelemetry-sdk 1.3

### ISSUE THREAD

**Issue by bolandoboy** [open-telemetry/opentelemetry-ruby-contrib#569]
I don't have a full list because I've only tested some of the instrumentation we use at my company, but I've found the following behaviour for Sinatra, Sidekiq and Faraday.

Making sure I use the latest Ruby image and Bundler version:

```
$ docker run --rm -it --workdir /test ruby bash
Unable to find image 'ruby:latest' locally
latest: Pulling from library/ruby
42cbebf8bc11: Pull complete 
9a0518ec5756: Pull complete 
356172c718ac: Pull complete 
dddcd3ceb998: Pull complete 
9cb2cffba570: Pull complete 
ba3cc5e5a031: Pull complete 
6c65a81b8ee4: Pull complete 
Digest: sha256:05ca729e257fc550f4228714a5f6c9f377d4dab92c30b2213340ddb7eec0b597
Status: Downloaded newer image for ruby:latest

root@8b1cc27be6c8:/test# bundle --version
Bundler version 2.4.10

root@8b1cc27be6c8:/test# gem update bundler
Updating installed gems
Updating bundler
Fetching bundler-2.4.17.gem
Successfully installed bundler-2.4.17
Gems updated: bundler

root@8b1cc27be6c8:/test# bundle --version
Bundler version 2.4.17

root@8b1cc27be6c8:/test# bundle init
Writing new Gemfile to /test/Gemfile

root@8b1cc27be6c8:/test# bundle add opentelemetry-sdk
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Fetching opentelemetry-api 1.2.0
Installing opentelemetry-api 1.2.0
Fetching opentelemetry-common 0.20.0
Fetching opentelemetry-registry 0.3.0
Fetching opentelemetry-semantic_conventions 1.10.0
Installing opentelemetry-common 0.20.0
Installing opentelemetry-registry 0.3.0
Installing opentelemetry-semantic_conventions 1.10.0
Fetching opentelemetry-sdk 1.3.0
Installing opentelemetry-sdk 1.3.0

root@8b1cc27be6c8:/test# bundle add opentelemetry-instrumentation-sidekiq
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Could not find compatible versions

Because opentelemetry-instrumentation-sidekiq < 0.7.0 depends on opentelemetry-api ~> 0.0
  and opentelemetry-instrumentation-sidekiq >= 0.7.0, < 0.8.0 depends on opentelemetry-api ~> 0.7.0,
  opentelemetry-instrumentation-sidekiq < 0.8.0 requires opentelemetry-api >= 0.0, < 1.A.
And because opentelemetry-instrumentation-sidekiq >= 0.8.0, < 0.9.0 depends on opentelemetry-api ~> 0.8.0
  and opentelemetry-instrumentation-sidekiq >= 0.9.0, < 0.10.0 depends on opentelemetry-api ~> 0.9.0,
  opentelemetry-instrumentation-sidekiq < 0.10.0 requires opentelemetry-api >= 0.0, < 1.A.
And because opentelemetry-instrumentation-sidekiq >= 0.10.0, < 0.11.0 depends on opentelemetry-api ~> 0.10.0
  and opentelemetry-instrumentation-sidekiq >= 0.11.0, < 0.12.0 depends on opentelemetry-api ~> 0.11.0,
  opentelemetry-instrumentation-sidekiq < 0.12.0 requires opentelemetry-api >= 0.0, < 1.A.
And because opentelemetry-instrumentation-sidekiq >= 0.12.0, < 0.13.0 depends on opentelemetry-api ~> 0.12.0
  and opentelemetry-instrumentation-sidekiq >= 0.13.0, < 0.14.0 depends on opentelemetry-common ~> 0.13.0,
  opentelemetry-instrumentation-sidekiq < 0.14.0 requires opentelemetry-api >= 0.0, < 1.A or opentelemetry-common ~> 0.13.0.
And because opentelemetry-instrumentation-sidekiq >= 0.14.0, < 0.15.0 depends on opentelemetry-common ~> 0.14.0
  and opentelemetry-instrumentation-sidekiq >= 0.15.0, < 0.16.0 depends on opentelemetry-common ~> 0.15.0,
  opentelemetry-instrumentation-sidekiq < 0.16.0 requires opentelemetry-api >= 0.0, < 1.A or opentelemetry-common ~> 0.13.0 OR ~> 0.14.0 OR ~> 0.15.0.
And because opentelemetry-instrumentation-sidekiq >= 0.16.0, < 0.17.0 depends on opentelemetry-common ~> 0.16.0
  and opentelemetry-instrumentation-sidekiq >= 0.17.0, < 0.18.0 depends on opentelemetry-common ~> 0.17.0,
  opentelemetry-instrumentation-sidekiq < 0.18.0 requires opentelemetry-api >= 0.0, < 1.A or opentelemetry-common ~> 0.13.0 OR ~> 0.14.0 OR ~> 0.15.0 OR ~> 0.16.0 OR ~> 0.17.0.
And because opentelemetry-instrumentation-sidekiq >= 0.18.0, < 0.19.0 depends on opentelemetry-common ~> 0.18.0
  and opentelemetry-instrumentation-sidekiq >= 0.19.0, < 0.19.1 depends on opentelemetry-common ~> 0.19.0,
  opentelemetry-instrumentation-sidekiq < 0.19.1 requires opentelemetry-api >= 0.0, < 1.A or opentelemetry-common ~> 0.13.0 OR ~> 0.14.0 OR ~> 0.15.0 OR ~> 0.16.0 OR ~> 0.17.0 OR ~> 0.18.0 OR ~> 0.19.0.
And because opentelemetry-instrumentation-sidekiq >= 0.19.1, < 0.20.1 depends on opentelemetry-common ~> 0.19.1
  and opentelemetry-instrumentation-sidekiq >= 0.20.1, < 0.20.2 depends on opentelemetry-common ~> 0.19.2,
opentelemetry-instrumentation-sidekiq < 0.20.2 requires opentelemetry-api >= 0.0, < 1.A or opentelemetry-common ~> 0.13.0 OR ~> 0.14.0 OR ~> 0.15.0 OR ~> 0.16.0 OR ~> 0.17.0 OR ~> 0.18.0 OR >= 0.19.0, <
0.20.A.
And because opentelemetry-instrumentation-sidekiq >= 0.20.2 depends on opentelemetry-common ~> 0.19.3
  and opentelemetry-sdk >= 1.2.0 depends on opentelemetry-api ~> 1.1,
  opentelemetry-sdk >= 1.2.0 requires opentelemetry-common ~> 0.13.0 OR ~> 0.14.0 OR ~> 0.15.0 OR ~> 0.16.0 OR ~> 0.17.0 OR ~> 0.18.0 OR >= 0.19.0, < 0.20.A.
So, because opentelemetry-sdk >= 1.3.0 depends on opentelemetry-common ~> 0.20
  and Gemfile depends on opentelemetry-sdk ~> 1.3,
  version solving has failed.
```

Please note that `opentelemetry-sdk` 1.3.0 was installed.

Installing both gems in one go with `bundle add opentelemetry-sdk opentelemetry-instrumentation-sidekiq` works, and it also works if you install the instrumentation before the SDK, but in both cases the SDK version installed is 1.2.1, which must be the highest compatible version that Bundler finds.

Is this something that needs to be dealt with? Or will it get "auto-solved" with the next release...? Don't know what the process is, but happy to help with bumping versions and testing if needed.

**Comment by arielvalentin** [comment]
Thanks for making us aware of this gem dependency problem. 

This looks like a tangled mess where the SDK depends on a specific version of the common gem but the instrumentations are pessimistically locking on that version, however the instrumentations don't have a dependency in the SDK. 

I'll take a look later today to see if we can get a fix out asap

**Comment by bolandoboy** [comment]
Hmm... While debugging locally, I have noticed that, for instance, `opentelemetry-instrumentation-sidekiq` fails to install from Rubygems but can be installed from the local copy with `--path`.

I see that the current [version 0.24.1 in Rubygems](https://rubygems.org/gems/opentelemetry-instrumentation-sidekiq/versions/0.24.1) depends on `opentelemetry-common ~> 0.19.3`, while in the repo that dependency has already been [updated to ~> 0.20.0](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/8fa20a19f474b646c6c7023780426caebdbe67c7/instrumentation/sidekiq/opentelemetry-instrumentation-sidekiq.gemspec#L29), and the gem version [remains at 0.24.1](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/8fa20a19f474b646c6c7023780426caebdbe67c7/instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/version.rb#L10).

Same thing happens for Faraday, Rack and Sinatra, from the small group I've tested.

Does this mean that this is just a matter of releasing the gems? (And I guess during the release process is when you bump versions...? Like Sidekiq 0.24.1 to 0.24.2 for example)

**Comment by arielvalentin** [comment]
I kicked off a release request but there wasn't anything pending a release other than `ottrace` propagators. I still need some time to look into this.

**Comment by bolandoboy** [comment]
I've been looking at the [release request logs](https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/5603651150/jobs/10250556988) and how Toys works, and I think the problem might be that only `chore` commits have been added since the last release for the affected gems.

Does that make sense, before I bury you in specific logs and pointers to Toys code? If yes, keep reading. If not, don't bother :)

From the logs:
```
[2023-07-19 20:12:03  INFO]  New version of opentelemetry-instrumentation-sidekiq is 0.24.2 by commit message analysis
...
[2023-07-19 20:12:05  INFO]  Starting with 43 gems in the release list
[2023-07-19 20:12:05  INFO]  1 gems remain after pruning those with no changes
...
```

In the Toys code I see that pruning happens when the `CHANGELOG` has been deemed not to have new entries ([code](https://github.com/dazuma/toys/blob/c22362c7c206866997b52590d00823e511c7863e/.toys/release/.lib/release_requester.rb#L331)), and new entries are added for `fix|feat|docs` commits, not `chore` (which makes all the sense) ([code](https://github.com/dazuma/toys/blob/c22362c7c206866997b52590d00823e511c7863e/.toys/release/.lib/release_requester.rb#L128) and [code](https://github.com/dazuma/toys/blob/c22362c7c206866997b52590d00823e511c7863e/.toys/release/.lib/release_requester.rb#L199C12-L199C12))

Commits for `opentelemetry-instrumentation-sidekiq` since last release:
```
* b12ea6d2 chore(deps-dev): update rubocop to ~> 1.54.1 in multiple gems (#555) (9 days ago) Robb Kidd
* cc244b9a chore(deps): update opentelemetry-common from 0.19.3 to 0.20.0 (#537) (3 weeks ago) Robb Kidd
* 72e1ab9c (... tag: opentelemetry-instrumentation-sidekiq/v0.24.1 ...)
```

**Comment by bolandoboy** [comment]
For `opentelemetry-propagator-ottrace` there's a `docs` commit that, as expected, generates an entry in the Changelog in #571.

The rest of `chore` commits don't generate entries.

```
* b12ea6d2 chore(deps-dev): update rubocop to ~> 1.54.1 in multiple gems (#555) (9 days ago) Robb Kidd
* 0f868b78 docs: Add some clarity to ottrace docs (#522) (12 days ago) Ariel Valentin
* b25ceafb chore: Combine dependabot rubocop bumps (#496) (7 weeks ago) Eric Mustin
* 499983c4 chore(deps-dev): update rubocop requirement from ~> 1.49.0 to ~> 1.50.2 in multiple gems (#437) (3 months ago) Robb Kidd
* 1b955ac8 (... tag: opentelemetry-propagator-ottrace/v0.21.0 ...)
```

**Comment by arielvalentin** [comment]
This release request should fix this: https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/569

**Comment by bolandoboy** [comment]
Awesome, the instrumentations in the OP now get installed correctly after the SDK.

I'm closing the issue as this is solved. Maybe we can talk somewhere else about testing the installation (if deemed necessary).

Thanks!

**Comment by arielvalentin** [comment]
@bolandoboy Thank you for verifying. I started a PR to run installs on latest versions of releases to try and avoid this problem and would appreciate your feedback on it.

https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/578
