### ISSUE TITLE
Return value of PG::Connection#column_values() is a PG::Result, not Array, with OpenTelemetry::Instrumentation::PG in use

### ISSUE THREAD

**Issue by Capncavedan** [open-telemetry/opentelemetry-ruby-contrib#570]
Without `OpenTelemetry::SDK` configured to use `OpenTelemetry::Instrumentation::PG`, the return value of `PG::Connection#column_values` is an Array containing bare strings (at least when selecting a text/string column).

With `OpenTelemetry::Instrumentation::PG` in use, the return value is a `PG::Result` object, and calling `to_a` on it returns an array of hashes, each with the column header as key and column/row value as value.

[PG method documentation](https://deveiate.org/code/pg/PG/Result.html#method-i-column_values) states:

```
column_values( n ) → array
Returns an Array of the values from the nth column of each tuple in the result.
```

**Runtime**

Operating system details: macOS Ventura 13.4.1 (c)
RUBY_ENGINE: MRI
RUBY_VERSION: 3.2.2
RUBY_DESCRIPTION: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]

**Gem versions**
pg (1.5.3)
opentelemetry-exporter-otlp (0.26.0)
opentelemetry-instrumentation-pg (0.25.2)
opentelemetry-sdk (1.3.0)

**Reproduction**

```rb
require 'pg'
require 'opentelemetry/sdk'
require 'opentelemetry/instrumentation/pg'
require 'opentelemetry-exporter-otlp'

if ENV['INSTRUMENT_PG'].to_s == 'true'
  OpenTelemetry::SDK.configure { |c| c.use 'OpenTelemetry::Instrumentation::PG' }
end

connection = PG.connect(dbname: ENV['NAME'], user: ENV['USER'], password: ENV['PASS'], host: ENV['HOST'], port: ENV['PORT'])

sql = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'"

subject = connection.exec(sql) { |result| result.column_values(0) }

puts subject.class.name
puts subject.first.class.name
```

Run with e.g. `NAME=database HOST=localhost PORT=5432 USER=user PASS=password ruby ./repro.rb` against a database with at least one table in it, you get:
```
Array
String
```

Run with e.g. `INSTRUMENT_PG=true NAME=database HOST=localhost PORT=5432 USER=user PASS=password ruby ./repro.rb` against a database with at least one table in it, you get:
```
PG::Result
Hash
```

**Comment by arielvalentin** [comment]
Thanks for this report. @ahayworth Any thoughts on this?

**Comment by ahayworth** [comment]
Well, that certainly is bizarre. If you look at the instrumentation, all we’re really doing is wrapping some methods in a span and calling super: https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb#L16

However, I don’t think we are Appraising any newer pg gem version than 1.4.5; and it looks like there were major, major changes in 1.5: https://github.com/ged/ruby-pg/blob/master/History.md

@Capncavedan - could I trouble you to check and see if this is reproducible on pg gem v1.4.5?

That would help narrow it down and save some time (I won’t be able to get a working repro environment up for another 1.5 weeks; I am going to be getting on a plane to Hawaii soon and will not be able to give this attention until the flight back ❤️)

**Comment by Capncavedan** [comment]
Sure thing!  I uninstalled pg 1.5.3 and installed 1.4.5.  It results in the same behavior as with 1.5.3.  (meaning - the issue still exists).

Have a great time in Hawaii!!

**Comment by Capncavedan** [comment]
@arielvalentin I'll see what I can figure out.  I've also found that it's only the block form that has an issue.  If I change line 15 of the repro script from this:

```rb
subject = connection.exec(sql) { |result| result.column_values(0) }
```

to this

```rb
subject = connection.exec(sql).column_values(0)
```

then the problem no longer manifests, in gem version 1.4.5 or 1.5.3.

**Comment by Capncavedan** [comment]
pr https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/574

**Comment by arielvalentin** [comment]
Should be fixed as part of https://github.com/open-telemetry/opentelemetry-ruby-contrib/releases/tag/opentelemetry-instrumentation-pg%2Fv0.25.3

**Comment by ahayworth** [comment]
Hooray! I got back from vacation and was just looking for the status of this, I'm quite happy to see that everyone was able to find a fix while I was away!

Thank you so much @Capncavedan and @arielvalentin for running this down 😄

**Comment by arielvalentin** [comment]
@Capncavedan please close this issue when you return and are able to verify the fix.

**Comment by Capncavedan** [comment]
This is all good!  Thanks, @arielvalentin and @ahayworth!
