### ISSUE TITLE
Improve documentation for sidekiq instrumentation

### ISSUE THREAD

**Issue by plantfansam** [open-telemetry/opentelemetry-ruby-contrib#65]
We've had users [tell us](https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/40) that our documentation for Sidekiq instrumentation is lacking. We should improve documentation on the library's options.

**Comment by bmulholland** [comment]
We're improving out Sidekiq telemetry now and it's both difficult and confusing without good docs. Normally I'd just add my +1 but need a comment for statebot.

**Comment by bmulholland** [comment]
Another comment for stalebot

**Comment by bmulholland** [comment]
And actually, while I'm here, I was reminded of this issue when reading OT discussion on HN a couple days ago: https://news.ycombinator.com/item?id=38971964

**Comment by arielvalentin** [comment]
@bmulholland we have limited capacity and we are looking for help in all aspects of maintenance and development including documentation. 

Would you be interested in contributing documentation for Sidekiq?

**Comment by bmulholland** [comment]
No, sorry, I don't have bandwidth for that. Totally get that others don't, either.
