### ISSUE TITLE
"stack level too deep" on redis trace

### ISSUE THREAD

**Issue by treyhyde** [open-telemetry/opentelemetry-ruby-contrib#662]
Rails 6 / unicorn application with `c.use_all`

This happens with and without prometheus instrumentation enabled.  So may or may not be related to open-telemetry/opentelemetry-ruby#352

```
/app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-api-0.12.1/lib/opentelemetry/context.rb:110:in `value': stack level too deep (SystemStackError)
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-api-0.12.1/lib/opentelemetry/trace.rb:62:in `current_span'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-sdk-0.12.1/lib/opentelemetry/sdk/trace/samplers/constant_sampler.rb:30:in `should_sample?'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-sdk-0.12.1/lib/opentelemetry/sdk/trace/samplers/parent_based.rb:56:in `should_sample?'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-sdk-0.12.1/lib/opentelemetry/sdk/trace/tracer.rb:47:in `start_span'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-api-0.12.1/lib/opentelemetry/trace/tracer.rb:28:in `in_span'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-instrumentation-redis-0.12.0/lib/opentelemetry/instrumentation/redis/patches/client.rb:18:in `call'
	from (eval):9:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-instrumentation-redis-0.12.0/lib/opentelemetry/instrumentation/redis/patches/client.rb:23:in `block in call'
	 ... 9346 levels...
	from /app/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `<main>'
	from /app/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
	from /app/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'
```

<img width="988" alt="Screen Shot 2021-01-26 at 3 43 14 PM" src="https://user-images.githubusercontent.com/62077/105921070-3b32b980-5fed-11eb-8428-3b6ce8767ebc.png">

**Comment by robertlaurin** [comment]
What about if you use the prepend mode for the prom exporter? OpenTelemetry continues to use prepending for patching instrumentation, prometheus exporter continues to default to using method aliasing, the two are still incompatible.
```rb
Rails.application.middleware.use PrometheusExporter::Middleware, instrument: :prepend
```

https://github.com/discourse/prometheus_exporter/tree/main#choosing-the-style-of-method-patching

**Comment by and0x000** [comment]
> What about if you use the prepend mode for the prom exporter? OpenTelemetry continues to use prepending for patching instrumentation, prometheus exporter continues to default to using method aliasing, the two are still incompatible.
> 
> ```ruby
> Rails.application.middleware.use PrometheusExporter::Middleware, instrument: :prepend
> ```
> 
> https://github.com/discourse/prometheus_exporter/tree/main#choosing-the-style-of-method-patching

Thank you, that seems to work

**Comment by arielvalentin** [comment]
@treyhyde Mind giving a try to using the suggested solution? https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/662#issuecomment-1711733437

If that does not work for you please reopen the issue.
