### ISSUE TITLE
Bunny error on receiving empty header message

### ISSUE THREAD

**Issue by 5cat** [open-telemetry/opentelemetry-ruby-contrib#663]
**Description of the bug**
When the message sent to a queue bunny listens to, and that message does not contain any headers, bunny fails on this [line](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/bunny/lib/opentelemetry/instrumentation/bunny/patch_helpers.rb#L40).

**Share details about your runtime**

Operating system details: Linux, Ubuntu 20.04 LTS
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.0.2"

**Comment by arielvalentin** [comment]
@5cat can you confirm that the issue is address with this release? https://github.com/open-telemetry/opentelemetry-ruby-contrib/releases/tag/opentelemetry-instrumentation-bunny%2Fv0.21.1
