### ISSUE TITLE
Remove Explicit Dependencies on ActiveSupport Core Extentions

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#705]
**Description of the bug**

Rails 7.1 is no longer auto-loading some core language extensions[^1], however we have a few instances of our instrumentation depending on those methods. 

We _must not_ rely on dependencies from any gem outside of the Ruby standard library. 

[^1]: https://github.com/rails/rails/commit/0170745b376acd150fec5f8cc57253cc1ffe0cf2

This is causing errors for some of our end users who are in the process of upgrading to Rails 7.1:

```console
ERROR -- : OpenTelemetry error: unexpected configuration error due to undefined method `blank?' for "eu-west-1":String - OpenTelemetry::SDK::ConfigurationError
```

I had replaced the usage of `blank?` in the `gruf` gem when adding test coverage for Rails 7.1 but it seems we still have references in at least the `grape` instrumentation.

cc: @muripic for Grape 

**Share details about your runtime**

Ruby 3.2 
Rails 7.1

**Comment by muripic** [comment]
Thanks for flagging, @arielvalentin ! I'll try to submit a PR fixing this today 😃
