### ISSUE TITLE
Add option for X-Ray remote sampling

### ISSUE THREAD

**Issue by gillesbergerp** [open-telemetry/opentelemetry-ruby-contrib#714]
We have successfully integrated OpenTelemetry with various of our Java applications (with X-Ray as a backend). Luckily, the OpenTelemetry Java SDK supports an X-Ray remote sampler that periodically polls X-Ray for sampling rules and applies them based on resource attributes (service name/type/...).
It would be great if the Ruby SDK would add support for this functionality as well since it makes managing sampling across a fleet of applications much easier.

**Comment by mwear** [comment]
Thanks for opening this issue. We've moved it to the contrib repo. Is there any chance you'd be interested in contributing this functionality?

**Comment by gillesbergerp** [comment]
Definitely. I just don't know how much time I can dedicate to this. I'd also need a little guidance as to where it would best fit in. Should we start a new `sampling` package similar to `instrumentaion` and `propagator`?

**Comment by arielvalentin** [comment]
@gillesbergerp yes, I think that creating a new **sampling** directory makes sense. 

I think each sampler should be encapsulated in its own gem.

**Comment by gillesbergerp** [comment]
I agree, that makes total sense. I'll see if I can find some time on the weekend and will reach out if I need anything.

**Comment by gillesbergerp** [comment]
X-Ray falls back to "1r/s or 5% after that" sampling rule if it cannot find any matching remote rules. I thought about making that implicit in the X-Ray sampling gem but then came to the conclusion that this could be interesting as a general option as well. At the very least, it will keep the X-Ray sampling implementation less complex. What do you think?
See https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/717

**Comment by gillesbergerp** [comment]
Please see https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/719 for the X-Ray gem. We'll also need adaptions in https://github.com/gillesbergerp/opentelemetry-ruby (specifically [here](https://github.com/gillesbergerp/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb#L167)) to allow for initializing the new sampler.
