### ISSUE TITLE
chore: OTel collector for exploratory testing

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#74]
Reviewing and and performing exploratory testing PRs would be made easier by being able to visualize the results in a tracing backend. 

This repository could provide contributors with an OTel collector service configured in the [main `docker-compose` file](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/docker-compose.yml) like we do for other services.  

Inspired by: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/72#issuecomment-1170077416

**Comment by plantfansam** [comment]
Great idea!
