### ISSUE TITLE
Unexpected behaviour in OpenTelemetry::Common::Utilities.untraced with opentelemetry-instrumentation-mysql2

### ISSUE THREAD

**Issue by pollosp** [open-telemetry/opentelemetry-ruby-contrib#788]
**Description of the bug**
Hello all, 
Not sure if this bug is for [opentelemetry-ruby](https://github.com/open-telemetry/opentelemetry-ruby) or for the [opentelemetry-ruby-contrib](https://github.com/open-telemetry/opentelemetry-ruby-contrib) repository. 

OpenTelemetry::Common::Utilities.untraced is not working as expected with `opentelemetry-instrumentation-mysql2` 

**Share details about your runtime**

Operating system details:  Docker ruby:3.1-slim-bullseye
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.1.1"

**Share a simplified reproduction if possible**
We have encountered an issue, detailed in this [test](https://github.com/open-telemetry/opentelemetry-ruby-contrib/compare/main...flywirecorp:opentelemetry-ruby-contrib:untraced-bug?expand=1). Despite using the 'untraced' option with MySQL instrumentation, traces still include spans that should be omitted. 

In contrast, when using net_http instrumentation , the behaviour aligns with expectations, as it correctly excludes the spans from the trace

Thanks.

**Comment by arielvalentin** [comment]
Untraced is unspecified behavior and is a convenience method provided by the Ruby SDK. It is inspired by other implementations and the reason it works with the Net HTTP instrumentation is that there is an explicit check for it as opposed to other instrumentations that rely on the sampler to make a decision about when to create a span.

@fbogsany If I recall correctly checking for untraced in a sampler was problematic but I don't recall what yall decided to do to get this working with other instrumentations. 

what do you recommend in this scenario?
