### ISSUE TITLE
OpenTelemetry::Instrumentation::PG: Provide option to omit db host in the span attributes 

### ISSUE THREAD

**Issue by NavindrenBaskaran** [open-telemetry/opentelemetry-ruby-contrib#839]
At present we're seeing our AWS RDS host under the `net.peer.name` attribute of the span. The host information is sensitive and we do not want to forward this information to a 3rd party monitoring tools.

Suggesting we can provide a `omit_db_host` option which can be used in the [transport_attrs](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb#L168) method as below:

```
def transport_attrs
  h = host

  attrs = if h&.start_with?('/')
            {
              'net.sock.family' => 'unix'
            }
          else
            {
              'net.transport' => 'ip_tcp',
              'net.peer.ip' => transport_addr,
              'net.peer.port' => transport_port
            }
          end

  attrs['net.peer.name'] = h unless config[:omit_db_host]
  attrs
end
```

**Comment by xuan-cao-swi** [comment]
Hi @NavindrenBaskaran , thanks for suggesting this issue.

Currently there is no [spec](https://github.com/open-telemetry/opentelemetry-specification) related to mask/omit over net.peer.name.

As per discussion during Ruby SIG, if you really need to omit the host information, there are two approaches that you can consider:

1. you can always overwrite/replace the transport_attrs function after initialization, for example:

```ruby
# custom_transport_attrs.rb
module OpenTelemetry
  module Instrumentation
    module PG
      module Patches
        module Connection
          def transport_attrs
            # your implementation
          end
        end
      end
    end
  end
end

# otel initialization
require_relative './custom_transport_attrs'
```

2. you can also customize the collector to omit the host information via [Transform Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md)
