### ISSUE TITLE
Enable gruf test suite Ruby 3.3

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#841]
Hey @arielvalentin - this has now been addressed and released, in connection with the grpc 1.61 release: https://rubygems.org/gems/gruf/versions/2.19.0

_Originally posted by @splittingred in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/797#discussion_r1478522637_

**Comment by arielvalentin** [comment]
@AS-AlStar Would you mind giving us a hand with this?

**Comment by AS-AlStar** [comment]
> @AS-AlStar Would you mind giving us a hand with this?

Hi! We are already use ruby 3.3, grpc 1.6.1, gruf 2.19 on our projects. No problems at the moment. I think you can enable it and everything will be fine. Pershaps there are specific examples with which there are difficulties?

**Comment by arielvalentin** [comment]
I had to disable the tests for 3.3 until the latest version of gruf was released (1.61). I would like to re-enable the tests but I think that means adding special cases in the appraisals for v1.61+

Is that something you can help us with?

**Comment by AS-AlStar** [comment]
you mean make a pull request and add it like this, right?

```
appraise 'gruf-2.19.0' do
  gem 'gruf', '~> 2.19.0'
  gem 'grpc', '~> 1.61.0'
end
```

**Comment by arielvalentin** [comment]
Yes please. But you may have to add conditionals if you want to support earlier versions

**Comment by AS-AlStar** [comment]
> Yes please. But you may have to add conditionals if you want to support earlier versions

Check please https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/872
