### ISSUE TITLE
Should `pg` gem be only a dev dependency for `pg` auto-instrumentation?

### ISSUE THREAD

**Issue by bixu** [open-telemetry/opentelemetry-ruby-contrib#86]
I'm working with an old ruby app at $job that has `pg` version `0.21.0` -- I _think_ this what causes the auto-instrumentation to fail...

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/37696bd2c5c8c58c072937e69834b562bf2c42a5/instrumentation/pg/opentelemetry-instrumentation-pg.gemspec#L37

**Comment by ericmustin** [comment]
The min compatible version for this instrumentation is, in fact, 1.1.0 https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/37696bd2c5c8c58c072937e69834b562bf2c42a5/instrumentation/pg/lib/opentelemetry/instrumentation/pg/instrumentation.rb#L12

What the reason for that min version is, i'm not totally sure. @ahayworth contributed this instrumentation, perhaps he could provide context on that min version?

**Comment by plantfansam** [comment]
Ah, I was confused — no reproduction steps necessary. @ericmustin beat me to it — not sure why we are requiring `1.1.0`. I guess we could generate an appraisal with the earlier gem version and see if specs are green?

**Comment by plantfansam** [comment]
See also https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/103
