### ISSUE TITLE
Redis instrumentation reports unknow_service

### ISSUE THREAD

**Issue by vzamanillo** [open-telemetry/opentelemetry-ruby-contrib#864]
The Redis instrumentation is reporting unknown service PIPELINED operations, it comes from a Rpush service, the Rpush gem is bundled into the application but Rpush does not run as embeeded process into the Rails application, it runs as a separate process (systemd).

![image](https://github.com/open-telemetry/opentelemetry-ruby-contrib/assets/10209695/e7c03137-0554-4d3d-80d4-96c91ed0d97e)

I think these operations should not be logged since Rpush instrumentation would need a dedicated plugin, plus it is out of process (the Rails process).

What is a PIPELINED operation? Does anyone know how to prevent this logging?

**Runtime**

Operating system details: CentOS Linux release 7.9.2009 (Core)
Rails: 6.1.5.1
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.2.2"
RUBY_DESCRIPTION: "ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]"

**initializers/opentelemetry.rb**

```ruby
require 'opentelemetry/sdk'
require 'opentelemetry/instrumentation/all'

OpenTelemetry::SDK.configure(&:use_all) unless Rails.env.development
```

**Trace details**

```
process.runtime.description: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
telemetry.sdk.version: 1.4.0
net.peer.port: 6378
process.command: /var/www/xxx/bin/rpush
telemetry.sdk.language: ruby
db.statement: MULTI ZRANGEBYSCORE ? ? ? ZREMRANGEBYSCORE ? ? ? EXEC
process.runtime.name: ruby
process.runtime.version: 3.2.2
process.pid: 6111
net.peer.name: 127.0.0.1
service.name: unknown_service
telemetry.sdk.name: opentelemetry
db.system: redis
```

**Comment by xuan-cao-swi** [comment]
I am not sure which third-party or vendor that you use for visualization of the trace, but the operation more like span name to me (as you can see from [redis instrumentation v4](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/opentelemetry-instrumentation-redis/v0.25.3/instrumentation/redis/lib/opentelemetry/instrumentation/redis/patches/redis_v4_client.rb#L39-L43) and [v5](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/opentelemetry-instrumentation-redis/v0.25.3/instrumentation/redis/lib/opentelemetry/instrumentation/redis/middlewares/redis_client.rb#L36)). I don't think redis instrumentation has operation attributes like [db.operation](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/semantic_conventions/lib/opentelemetry/semantic_conventions/trace.rb#L53-L55).

I am not super familiar with Redis, but from the `db.statement: db.statement: MULTI ZRANGEBYSCORE ? ? ? ZREMRANGEBYSCORE ? ? ? EXEC`, it seems like the rpush is executing mutliple command `ZRANGEBYSCORE`, and current redis instrumentation has to treat it as a pipeline operation.

For the unknown_service, it's likely the application didn't setup the service name for otel during configuration or through environmental variable. The default service name is [unknown_service](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/sdk/lib/opentelemetry/sdk/resources/resource.rb#L34). To setup the service name:

```
export OTEL_SERVICE_NAME=the_service_name_you_want
```
or see https://opentelemetry.io/docs/languages/ruby/getting-started/#instrumentation
```ruby
OpenTelemetry::SDK.configure do |c|
  c.service_name = 'dice-ruby'
  c.use_all() # enables all instrumentation!
end
```

**Comment by vzamanillo** [comment]
Hey!

Thank you for helping me with this!!.

(I'm using Signoz)

yes, you are right but the thing is, Rpush runs as a separate process (out of the main Rails app process), the Rpush gem is bundled with the Rails app because it has the dependency in the Gemfile (for comfort reasons) but it is started using systemd with an specific unit script, this way

**/etc/systemd/system/rpush.service**
```shell
...
START_COMMAND="$RVM_PATH $GEMSET do bundle exec rpush start -p $RPUSH_PID -c $RPUSH_CONFIG -e $R_ENV"
STOP_COMMAND="$RVM_PATH $GEMSET do bundle exec rpush stop -p $RPUSH_PID -c $RPUSH_CONFIG -e $R_ENV"

RPUSH_USAGE="Usage: $0 {start|stop|kill|status|restart}"

rpush_pid() {
  if test -f "$RPUSH_PID"; then
    echo `ps -ef | grep $(<"$RPUSH_PID") | grep -v grep | tr -s " " | cut -d" " -f2`
  fi
}

start() {
  pid=$(rpush_pid)
  if [ -n "$pid" ]; then
    echo -e "Rpush is already running (pid: $pid)"
  else
    echo -e "Starting Rpush..."
    /bin/sh -c "cd $WORKING_DIR && exec $START_COMMAND"
    status
  fi
  return 0
}
...
```

that's why the redis instrumentation reports an unknown service, because Rpush is not configured.

The main Rails app (running over a Phusion Passenger server) is properly initialized and reports all the instrumented data as expected.

```
passenger_env_var OTEL_EXPORTER otlp;
passenger_env_var OTEL_SERVICE_NAME staging;
passenger_env_var OTEL_EXPORTER_OTLP_ENDPOINT http://localhost:xxxx;
```

I understand (i think so xD) how the redis instrumentation works but what I am trying to understand is why it is logging data from an outside process, I did the setup for the Rails application (the initializer above in my previous note) not for Rpush (Rpush is not an embedded process of the Rails application).

**Comment by xuan-cao-swi** [comment]
After briefly looked at the rpush gem, I think rpush will load the rails again at [load_rails_environment](https://github.com/rpush/rpush/blob/master/lib/rpush/cli.rb#L118). In my simple rails' setup, environment.rb calls `Rails.application.initialize!`. If that's also your rails' setup, I think the rpush reinitialize the opentelemetry in its process. However, it's just a guessing, not sure if that's the case.

**Comment by vzamanillo** [comment]
Hey!

oh, makes sense, thank you very much for your help, I will careful take a look to confirm.

**Comment by vzamanillo** [comment]
Confirmed, thank you for the help!!!
