### ISSUE TITLE
Grape instrumentation adapter

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby-contrib#9]
Convert Datadog instrumentation for Grape to OpenTelemetry. 

See
  * [Datadog porting guide](https://github.com/open-telemetry/opentelemetry-ruby/blob/master/adapters/datadog-porting-guide.md)
  * [Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions)
  * [Datadog implementation](https://github.com/DataDog/dd-trace-rb/tree/master/lib/ddtrace/contrib/grape)

**Comment by muripic** [comment]
Hi there!

We've picked up the Grape instrumentation at Catawiki and we're already working on it.
We are using the ddog implementation as a reference, using ActiveSupport notifications. It's still a WIP, but just for reference here's the fork we're working on: https://github.com/catawiki/opentelemetry-ruby-contrib 😄
