### ISSUE TITLE
Sidekiq `messaging.operation` name "process" misaligned with semantic conventions

### ISSUE THREAD

**Issue by hibachrach** [open-telemetry/opentelemetry-ruby-contrib#924]
I notice that the Sidekiq middleware [uses the term "process"](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/35f3942715bccd3bff293ab3eb386d1da7b8d918/instrumentation/sidekiq/lib/opentelemetry/instrumentation/sidekiq/middlewares/server/tracer_middleware.rb#L24) instead of [those specified in the (still `experimental`) messaging section of the semantic convention specification](https://opentelemetry.io/docs/specs/semconv/messaging/messaging-spans/#operation-names) for the `messaging.operation` attribute.

Is this a recent change? it seems in #648 it was different which was only a few months ago.

**Comment by kaylareopelle** [comment]
Hi @hibachrach, thanks for bringing this to our attention! My apologies on the delay in response.

I'm not sure I entirely understand your question, so I have a few follow-ups:
* It looks like `process` is one of the valid operation categories for the messaging section. Is there a different operation you think would be more accurate in the context of Sidekiq's server?
* [The changes in #648 were made to the client middleware](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/648/files#diff-fa05ab9770cadc0c54ff3f5341bb37219a5d0f263a95791c400c11b3b37964bcR28-R29), not the server middleware. They updated `send` to `publish`. Is there a different operation that seems more appropriate for the client? 
* Am I misunderstanding your question entirely and there's something else we should be looking into?

**Comment by hibachrach** [comment]
No apologies necessary! Appreciate your work in open source 😄

Reading my question again, I have no idea what I as asking. Everything seems fine and my ask doesn't make any sense (perhaps I was looking at the wrong version of the OTel docs). Apologies for the misunderstanding!
