### ISSUE TITLE
Request for new component: Baggage Span Processor

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-ruby-contrib#934]
The Honeycomb distro currently provides a Span processor that takes items from the baggage and adds those items as attributes onto spans. We'd like to donate this code upstream if there's an interest from the community, the code is pretty minimal:
https://github.com/honeycombio/honeycomb-opentelemetry-ruby/blob/main/lib/honeycomb/opentelemetry/trace/baggage_span_processor.rb

**Comment by arielvalentin** [comment]
Thanks for sharing. 

This would be appropriate for our contrib repo. If it makes its way into the spec then we can move it into the core SDK.

@robbkidd would you mind helping shepard this contribution along?
