### ISSUE TITLE
Add Triager Role

### ISSUE THREAD

**Issue by plantfansam** [open-telemetry/opentelemetry-ruby-contrib#94]
The [OpenTelemetry community  doc](https://github.com/open-telemetry/community/blob/main/community-membership.md) identifies a triager role:

triager | assist with project management and backlog organization. | nominated by a maintainer. attend meetings for one month. | CONTRIBUTING, CODEOWNERS, or the README.
-- | -- | -- | --

We should add this role to this repo

**Comment by ahayworth** [comment]
I think I said this in a Slack thread - I'm not opposed to a `-triager` role, but I also don't think our volume of issues warrants it at the moment.
