### ISSUE TITLE
Ruby `head` canary test coverage

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#940]
The `setup-ruby` action seems to support installing Ruby `head`, which I presume means we are able to work off the latest development version pulled from GitHub. 

<https://github.com/ruby/setup-ruby/blob/6bd3d993c602f6b675728ebaecb2b569ff86e99b/ruby-builder-versions.json#L16C6-L16C10>

Adding test coverage for `head` will allow us to prepare for future unexpected issues and incompatibility but should not prevent us from releasing.

**Comment by dmathieu** [comment]
If the test suite runs for `head` on every PR, an unrelated failure would break every CI run.
It feels like this should run at regular intervals (weekly?) and open an issue if there's a failure.

**Comment by arielvalentin** [comment]
@dmathieu I should have been more explicit but that is what I mean by making a `canary` build as opposed to having it run on CI every time a PR is opened or merged:  

> Adding test coverage for head will allow us to prepare for future unexpected issues and incompatibility but should not prevent us from releasing.
