### ISSUE TITLE
Use semconv span naming in ActionPack

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#961]
`action_pack` currently overrides the `server` span name to a value that does not align with semantic conventions. Per the specification[^1]
 
> HTTP spans MUST follow the overall [guidelines for span names](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.31.0/specification/trace/api.md#span).
> 
> HTTP server span names SHOULD be {method} {http.route} if there is a (low-cardinality) http.route available (see below for the exact definition of the [{method}](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#method-placeholder) placeholder).
> 
> If there is no (low-cardinality) http.route available, HTTP server span names SHOULD be [{method}](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#method-placeholder).
> 
> HTTP client spans have no http.route attribute since client-side instrumentation is not generally aware of the “route”, and therefore HTTP client span names SHOULD be [{method}](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#method-placeholder).
> 
> The {method} MUST be {http.request.method} if the method represents the original method known to the instrumentation. In other cases (when {http.request.method} is set to _OTHER), {method} MUST be HTTP.
> 
> Instrumentation MUST NOT default to using URI path as span name, but MAY provide hooks to allow custom logic to override the default span name.

In this case the span name is set to RubyDoc naming style, with the class name of the controller followed by an `#` then the action:

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/10e766e13e7734f284807af4099e0858ca85cf4f/instrumentation/action_pack/lib/opentelemetry/instrumentation/action_pack/handlers/action_controller.rb#L29

I propose the span name be set to either of the following values:

- `>= 7.1` [`ActionDispatch::Request#route_uri_pattern`](https://api.rubyonrails.org/classes/ActionDispatch/Request.html#method-i-route_uri_pattern) 
- `< 7.1` `#{method} /#{underscore(controller)}/#{action}`

In addition to that, we should restore the `http.route` attribute. 

[^1]: https://opentelemetry.io/docs/specs/semconv/http/http-spans/#name

**Comment by robertlaurin** [comment]
+1 for [ActionDispatch::Request#route_uri_pattern](https://api.rubyonrails.org/classes/ActionDispatch/Request.html#method-i-route_uri_pattern)

Personally I would like to keep the existing naming convention as config opt if possible, it's just such a useful railism and Action Pack is rails instrumentation, just saying 😄

**Comment by robbkidd** [comment]
> ... I would like to keep the existing naming convention ...  it's just such a useful railism

I've heard similar from other Rails folks instrumenting with OTel. The Rails world currently thinks in the names Rails has given and not so much thinking in the OTel semantics. Maybe that will change as more people adopt OTel and polyglot shops start wondering why their Rails web request handling spans are named differently than the spans from other services in their larger system.

**Comment by karmingc** [comment]
Shouldn't >= 7.1  be `#{request.method} #{request.route_uri_pattern}` instead?

**Comment by arielvalentin** [comment]
> Shouldn't >= 7.1 be `#{request.method} #{request.route_uri_pattern}` instead?

@karmingc yes!

**Comment by codeboten** [comment]
Would it be possible to also bring back the `http.route` attribute that was removed in https://github.com/rails/rails/pull/47129 as part of this issue or would it make more sense to do it separately?

**Comment by arielvalentin** [comment]
Yes, I think that we should also add the http.route attribute as part of this issue.

**Comment by arielvalentin** [comment]
Heads up. I started working on this and I am not in love with `route_uri_pattern`. 

I will submit a PR so that you all can see for yourselves that the `rails route` format is not exactly what I was expecting.
