### ISSUE TITLE
[inst-rack] rack_events + untraced_endpoints will still emit child spans of those endpoint

### ISSUE THREAD

**Issue by robbkidd** [open-telemetry/opentelemetry-ruby-contrib#962]
**Description of the bug**

There's a difference in behavior for untraced endpoints when using middleware vs the newer implementation using Rack events.

* middleware: wraps call with the untraced helper from Utilities which sets untraced in the context used by child spans
* rack events: early returns from Rack's on_start and on_end handlers but does not change the context, so child spans get traced

I owe more details here! Opening as a placeholder for me to add more later.

**Comment by robertlaurin** [comment]
https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/965#issuecomment-2099275533

**Comment by robertlaurin** [comment]
https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/968
