### ISSUE TITLE
Add cspell to our CI

### ISSUE THREAD

**Issue by kaylareopelle** [open-telemetry/opentelemetry-ruby-contrib#980]
The [OpenTelemetry documentation style guide](https://opentelemetry.io/docs/contributing/style-guide/) uses cspell to check spelling: https://cspell.org/ 

Add this to the Ruby agent repository to check markdown documentation.

We could also consider trying to apply [their existing spelling exceptions file this repository.](https://github.com/open-telemetry/opentelemetry.io/blob/main/.cspell.yml)

**Comment by hannahramadan** [comment]
I'll take this!
