### ISSUE TITLE
ActiveModelSerializer instrumentation does not make the span current

### ISSUE THREAD

**Issue by renchap** [open-telemetry/opentelemetry-ruby-contrib#992]
**Description of the bug**

Spans occuring during a render call using AM:S are not set as children span of the AM:S render span

<img width="1104" alt="image" src="https://github.com/open-telemetry/opentelemetry-ruby-contrib/assets/42070/aad45677-13d9-414d-8c0a-74da73018dfe">

Here, the spans below the serializer are made by the serializer code.

**Share details about your runtime**

Operating system details: Linux, Ubuntu 20.04 LTS
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.2.2"
RUBY_DESCRIPTION: "ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]"

**Share a simplified reproduction if possible**

No reproduction, but the issue is that the event handler is setting itself as the current span here: https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/active_model_serializers/lib/opentelemetry/instrumentation/active_model_serializers/event_handler.rb#L14-L20

Pinging @robbkidd as he helped me on this

**Comment by robbkidd** [comment]
Thanks for opening this, @renchap! 

My hypothesis is that ActiveModelSerializers instrumentation is using [an older style of AS::Notification event subscription](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/c4e9fc8a9f1eda1a28b9b983df7cc7540f82234f/instrumentation/active_model_serializers/lib/opentelemetry/instrumentation/active_model_serializers/instrumentation.rb#L37-L41) and [handling](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/c4e9fc8a9f1eda1a28b9b983df7cc7540f82234f/instrumentation/active_model_serializers/lib/opentelemetry/instrumentation/active_model_serializers/event_handler.rb#L14-L20). It does not start the span in a way that makes the serialization span the current span while it is doing work.

**Comment by renchap** [comment]
Still a valid issue!

**Comment by renchap** [comment]
Still valid!
